version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=tacofancy
      - POSTGRES_USER=tacofancy
      - POSTGRES_PASSWORD=tacofancy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: