"""Adding full name to contributors

Revision ID: 3cdc506203bb
Revises: 4e3c8db63bb7
Create Date: 2013-11-08 20:21:29.169837

"""

# revision identifiers, used by Alembic.
revision = '3cdc506203bb'
down_revision = '4e3c8db63bb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributor', sa.Column('full_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributor', 'full_name')
    ### end Alembic commands ###
