"""Adding slug field

Revision ID: 42f7e2ac0c98
Revises: None
Create Date: 2013-11-06 20:07:37.909974

"""

# revision identifiers, used by Alembic.
revision = '42f7e2ac0c98'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_layer', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('condiment', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('full_taco', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('mixin', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('seasoning', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('shell', sa.Column('slug', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shell', 'slug')
    op.drop_column('seasoning', 'slug')
    op.drop_column('mixin', 'slug')
    op.drop_column('full_taco', 'slug')
    op.drop_column('condiment', 'slug')
    op.drop_column('base_layer', 'slug')
    ### end Alembic commands ###
