"""Adding Contributors and relations

Revision ID: 4e3c8db63bb7
Revises: 42f7e2ac0c98
Create Date: 2013-11-08 15:41:11.281282

"""

# revision identifiers, used by Alembic.
revision = '4e3c8db63bb7'
down_revision = '42f7e2ac0c98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributor',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('gravatar', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('contrib_mixin',
    sa.Column('contrib_username', sa.String(), nullable=True),
    sa.Column('mixin_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contrib_username'], ['contributor.username'], ),
    sa.ForeignKeyConstraint(['mixin_url'], ['mixin.url'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('contrib_seasoning',
    sa.Column('contrib_username', sa.String(), nullable=True),
    sa.Column('seasoning_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contrib_username'], ['contributor.username'], ),
    sa.ForeignKeyConstraint(['seasoning_url'], ['seasoning.url'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('contrib_shell',
    sa.Column('contrib_username', sa.String(), nullable=True),
    sa.Column('shell_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contrib_username'], ['contributor.username'], ),
    sa.ForeignKeyConstraint(['shell_url'], ['shell.url'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('contrib_baselayer',
    sa.Column('contrib_username', sa.String(), nullable=True),
    sa.Column('baselayer_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['baselayer_url'], ['base_layer.url'], ),
    sa.ForeignKeyConstraint(['contrib_username'], ['contributor.username'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('contrib_condiment',
    sa.Column('contrib_username', sa.String(), nullable=True),
    sa.Column('condiment_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['condiment_url'], ['condiment.url'], ),
    sa.ForeignKeyConstraint(['contrib_username'], ['contributor.username'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('contrib_fulltaco',
    sa.Column('contrib_username', sa.String(), nullable=True),
    sa.Column('full_taco_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contrib_username'], ['contributor.username'], ),
    sa.ForeignKeyConstraint(['full_taco_url'], ['full_taco.url'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contrib_fulltaco')
    op.drop_table('contrib_condiment')
    op.drop_table('contrib_baselayer')
    op.drop_table('contrib_shell')
    op.drop_table('contrib_seasoning')
    op.drop_table('contrib_mixin')
    op.drop_table('contributor')
    ### end Alembic commands ###
