"""Add SyncMetadata table for tracking incremental updates

Revision ID: bebbb2c0f0e7
Revises: 
Create Date: 2025-08-17 19:57:06.984900

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bebbb2c0f0e7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sync_type", sa.String(length=50), nullable=False),
        sa.Column("last_commit_sha", sa.String(length=40), nullable=True),
        sa.Column("last_sync_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_metadata")
    # ### end Alembic commands ###
